#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*              Anil Madhavapeddy, OCaml Labs                             *
#*                                                                        *
#*   Copyright 2014 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

sudo: false
language: c
git:
  submodules: false
script: bash -ex .travis-ci.sh

# also run tests under the debug runtime
matrix:
  include:
  - compiler: gcc
    os: linux
    env:
    - XARCH=x86_64
    - USE_RUNTIME=d
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - XARCH=x86_64
  - XARCH=i386
